export const projects = [
  {
    id: "next-js-website",
    title: "next-js-website",
    url: "https://next-js-website1.vercel.app/",
    lastCommitMsg: "Fix Some Issue",
    branch: "main",
    duration: "55d",
    gitPlatform: "github",
  },
  {
    id: "nuxt-js-website",
    title: "nuxt-js-website",
    url: "https://nuxt-js-website1.vercel.app/",
    lastCommitMsg: "Fix Some Issue",
    branch: "main",
    duration: "25d",
    gitPlatform: "github",
  },
  {
    id: "next-website",
    title: "next-website",
    url: "https://next-website1.vercel.app/",
    lastCommitMsg: "Fix Some Issue",
    branch: "main",
    duration: "35d",
    gitPlatform: "github",
  },
  {
    id: "next-ecommerce-website",
    title: "next-ecommerce-website",
    url: "https://next-ecommerce-website1.vercel.app/",
    lastCommitMsg: "Fix Some Issue",
    branch: "main",
    duration: "12d",
    gitPlatform: "github",
  },
  {
    id: "next-app-website",
    title: "next-app-website",
    url: "https://next-app-website1.vercel.app/",
    lastCommitMsg: "Fix Some Issue",
    branch: "main",
    duration: "65d",
    gitPlatform: "github",
  },
  {
    id: "next-typescript-website",
    title: "next-typescript-website",
    url: "https://next-typescript-website1.vercel.app/",
    lastCommitMsg: "Fix Some Issue",
    branch: "main",
    duration: "76d",
    gitPlatform: "github",
  },
];
